# Generated by Django 4.0.2 on 2022-02-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_users_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Savol matni')),
                ('question_type', models.SmallIntegerField(choices=[(1, 'Text'), (2, 'Select')], default=1, help_text='Savol turi')),
                ('is_active', models.BooleanField(default=False, help_text='Buni belgilasayiz savol foydalanuvchiga boradi')),
            ],
            options={
                'verbose_name': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='QuestionValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Savol varianti', max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg.questions')),
            ],
            options={
                'verbose_name': 'Savolning javoblari',
            },
        ),
    ]
