# Generated by Django 4.0.2 on 2022-02-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField()),
                ('tg_username', models.CharField(blank=True, max_length=150, null=True)),
                ('tg_firstname', models.CharField(blank=True, max_length=150, null=True)),
                ('tg_lastname', models.CharField(blank=True, max_length=150, null=True)),
                ('user_status', models.SmallIntegerField(choices=[(1, 'Botga start bosgan'), (2, 'Savollarga javob bergan'), (3, "Moderatsiyadan o'tmadi"), (4, "Moderatsiyadan o'tdi")], default=1)),
            ],
            options={
                'verbose_name': 'Foydalanuvchilar',
            },
        ),
    ]
