# Generated by Django 4.0.2 on 2022-03-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0007_answers_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(help_text='Google docsdagi page nomi', max_length=40)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Docs page',
            },
        ),
    ]
