# Generated by Django 4.0.2 on 2022-03-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0008_docspage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionvalues',
            options={},
        ),
        migrations.AddField(
            model_name='questions',
            name='colum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
