# Generated by Django 4.0.2 on 2022-03-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0011_docskeys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name_plural': 'Foydalanuvchilar javoblari'},
        ),
        migrations.AlterModelOptions(
            name='docskeys',
            options={'verbose_name_plural': 'Docs Keys'},
        ),
        migrations.AlterModelOptions(
            name='docspage',
            options={'verbose_name_plural': 'Docs page'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='senddata',
            options={'verbose_name_plural': 'Other texts'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
