# Generated by Django 4.0.2 on 2022-03-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0012_alter_answers_options_alter_docskeys_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='tg_id',
            field=models.BigIntegerField(),
        ),
    ]
